trigger:
  branches:
    include:
      - master
  paths:
    include:
      - '*'
    exclude:
      - 'VERSION.txt'
      - 'changelog.md'
      - 'packaging/*'
      - 'documentation/*'

pr:
  branches:
    include:
      - '*'  # Allow PRs to target any branch
  paths:
    include:
      - '*'  # Trigger for all files
    exclude:
      - 'VERSION.txt'
      - 'changelog.md'
      - 'packaging/*'
      - 'documentation/*'

jobs:
- job: PR_Validation
  condition: and(succeeded(), not(startsWith(variables['System.PullRequest.SourceBranch'], 'refs/heads/currency/')))
  steps:
    - script: echo "Running pipeline for PR"
