trigger:
  branches:
    include:
      - main
  paths:
    include:
      - '*'
    exclude:
      - 'VERSION.txt'
      - 'changelog.md'

pr:
  branches:
    include:
      - '*'
    exclude:
      - 'currency/*'
  paths:
    include:
      - '*'
    exclude:
      - 'VERSION.txt'
      - 'changelog.md'

jobs:
  - job: TestBranchFilter
    steps:
      - script: echo "Testing branch and path filters"
